### ISSUE TITLE
write_page() throws an Encoding::CompatibilityError for chinese characters

### ISSUE THREAD

**Issue by nirnanaaa** [gollum/gollum-lib#104] opened 2014-10-24 09:58 UTC
Hey,

I am trying to fix an issue, where the page name is something chinese: `你是我的中关星`. Saving the page via:

```ruby

class B

  def self.test(wiki, name)
    
    canonicalized_filename = Gollum::Page.canonicalize_filename(name)
    format = :markdown
    content = "abc"
    commit = {
      name: "nirnanaaa",
      email: "mosny@zyg.li",
      message: "created abc"
    }
    path_name = "/"
    
    wiki.write_page(canonicalized_filename, format, content, commit, path_name)
  end
end

wiki = User.wiki
 => #<Gollum::Wiki:70304539248780 /Volumes/Documents/GollumRails4Test/demoapp.git>

2.1.2 :003 > name = "你是我的中关星"

2.1.2 :003 > B.test(wiki)
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
```
```
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:176:in `%'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:176:in `block in write_tree'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:171:in `each'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:171:in `write_tree'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:123:in `commit'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gollum-lib-3.0.0/lib/gollum-lib/committer.rb:170:in `commit'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gollum-lib-3.0.0/lib/gollum-lib/wiki.rb:340:in `write_page'
	from /Volumes/Documents/chin.rb:24:in `test'
	from (irb):3
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
... 3 levels...
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `block in load'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/commands/rails.rb:6:in `call'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:180:in `block in serve'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:153:in `fork'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:153:in `serve'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/nirnanaaa/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nirnanaaa/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'2.1.2 :004 >
```

I have then edited the file `gitlab-grit/lib/grit/index.rb` at line 176 and changing the `[tmode, obj.name, sha]` to `[tmode, obj.name, sha.force_encoding("UTF-8")]` works, but is not a good practice.

Some tests:

* Create a page with the filename in english and the content in englisch - WORKS
* Create a page with the filename in english and the content in chinese - WORKS
* Create a page with the filename in chinese and the content in english - DOES NOT WORK

After trying to create the page with `write_page` once, each single of those tests in the current session will fail:

```ruby
2.1.2 :007 >   name = "testpage"
 => "testpage"
2.1.2 :008 > B.test(wiki, name)
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
```

```
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:176:in `%'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:176:in `block in write_tree'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:171:in `each'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:171:in `write_tree'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gitlab-grit-2.6.12/lib/grit/index.rb:123:in `commit'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gollum-lib-3.0.0/lib/gollum-lib/committer.rb:170:in `commit'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/gollum-lib-3.0.0/lib/gollum-lib/wiki.rb:340:in `write_page'
	from /Volumes/Documents/chin.rb:24:in `test'
	from (irb):3
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
... 3 levels...
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `block in load'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/commands/rails.rb:6:in `call'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:180:in `block in serve'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:153:in `fork'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:153:in `serve'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
	from /Users/nirnanaaa/.rvm/gems/ruby-2.1.2/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/nirnanaaa/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nirnanaaa/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'2.1.2 :004 >
```

Debugging things a little further I found the following:

```ruby
    now_tree.contents.each do |obj|
        sha = [obj.id].pack("H*")
        k = obj.name
        k += '/' if (obj.class == Grit::Tree)
        tmode = obj.mode.to_i.to_s  ## remove zero-padding
        debugger
        tree_contents[k] = "%s %s\0%s" % [tmode, obj.name, sha]
      end if

(rdb:1) tmode.encoding
#<Encoding:US-ASCII>
(rdb:1) tmode
"100644"
(rdb:1) obj.name.encoding
#<Encoding:UTF-8>
(rdb:1) obj.name
"你是我的中关星.md"
(rdb:1) sha.encoding
#<Encoding:ASCII-8BIT>
```
the emergence of Chinese, and then throws the  Exception.

Hope someone can help.

Thanks a lot

**Comment by dometto** [comment] 2015-01-03 19:48
Took a look at this and encountered some surprising results. @nirnanaaa's test case works *both* with the rugged adapter **and** the grit adapter. However, in both cases, when trying to create a page with a name containing utf-8 cases via the gollum webapp, the pagename is transliterated (e.g. `'你是我的中关星'` => `'Ni Shi Wo De Zhong Guan Xing'`). Conclusion: both grit and rugged now support utf-8 filenames, but gollum is messing up the page title. The problem is thus not in gollum-lib but in gollum, so I'm closing this and re-opening https://github.com/gollum/gollum/issues/830. See there for further diagnostics.

**Closed by dometto** 2015-01-03 19:48 UTC

**Comment by nirnanaaa** [comment] 2015-01-04 16:25
let me try with gollum_rails. I will report back
