### ISSUE TITLE
Upgrade from 4.2.0 to 4.2.1 labels links in sidebar/header/footer as "absent".

### ISSUE THREAD

**Issue by bsdfirst** [gollum/gollum-lib#222] opened 2016-09-22 02:06 UTC
After upgrade from `4.2.0` to `4.2.1`, all internal links in `_Sidebar`, `_Header`, and `_Footer` (at the top level) are assigned the class `absent` and are thus coloured red.  Internal links within the main page body are classified correctly.  Downgrade of `gollum-lib` to `4.2.0` resolves the issue.

Discovered in production running under unicorn; however, reproduced running gollum on the commandline with a clean installation.  Gem versions as below:

```
asciidoctor (1.5.4)
bigdecimal (1.2.8)
builder (3.2.2)
bundler (1.13.1)
charlock_holmes (0.7.3)
creole (0.5.0)
did_you_mean (1.0.0)
diff-lcs (1.2.5)
expression_parser (0.9.0)
github-markdown (0.6.9)
github-markup (1.4.0)
gitlab-grit (2.8.1)
gollum (4.0.0)
gollum-grit_adapter (1.0.1)
gollum-lib (4.2.0)
htmlentities (4.3.4)
io-console (0.4.5)
json (1.8.3)
kramdown (1.8.0, 1.6.0)
mime-types (2.99.3)
mini_portile2 (2.1.0)
minitest (5.8.4)
mustache (0.99.8)
net-telnet (0.1.1)
nokogiri (1.6.8)
org-ruby (0.9.12)
pkg-config (1.1.7)
posix-spawn (0.3.11)
power_assert (0.2.7)
psych (2.0.17)
rack (1.6.4)
rack-protection (1.5.3)
rake (10.5.0)
rdoc (4.2.1)
RedCloth (4.3.2)
rouge (2.0.6, 1.11.1)
rubypants (0.5.0)
sanitize (2.1.0)
sinatra (1.4.7)
stringex (2.5.2)
test-unit (3.1.7)
tilt (2.0.5)
twitter-text (1.14.0)
unf (0.1.4)
unf_ext (0.0.7.2)
useragent (0.14.0, 0.10.0)
wikicloth (0.8.3)
```

**Comment by bartkamphorst** [comment] 2016-09-22 10:03
Thanks for reporting this @bsdfirst . I think this issue should be resolved in `master`, so with the next release.

**Comment by dometto** [comment] 2017-04-14 12:50
@bartkamphorst I think this can be closed?

**Comment by bartkamphorst** [comment] 2017-04-14 13:01
It's probably wise to test this in 5.x first, just to be sure.

**Comment by dometto** [comment] 2018-10-01 16:30
Cannot reproduce on 5.x

**Closed by dometto** 2018-10-01 16:30 UTC
