### ISSUE TITLE
Allow serving wiki from subdirectory

### ISSUE THREAD

**Issue by deric** [gollum/gollum-lib#133] opened 2015-01-11 17:18 UTC
Instead of `base_path` argument which just modifies the links, would it be possible to introduce an argument that would change directory which gollum-lib considers as root?

It would be very convenient, e.g. for [gollum#937](https://github.com/gollum/gollum/issues/937).

**Comment by dometto** [comment] 2015-01-11 19:09
The `--page-file-dir` option comes as close to that as possible. (The actual root has to be the root of the repo for git to work at all). What I think you want is an additional option that automatically prefixes every requested path with the value of `--page-file-dir`, so that's not displayed as part of URI's and titles. That seems reasonable, but as I remarked, before we implement that, we would have to clean up and make consistent the way gollum is constructing URI's and titles at the moment.

For example, the tag filter is constructing URI's by joining `wiki.base_path` and page/file paths manually in two places. That's asking for trouble. There should be a single helper that constructs the URI for a page or file based on `page_file_dir`, `base_path`, and whatever other variables are relevant. Both gollum-lib and gollum should use that helper whenever constructing URI's.

**Comment by dometto** [comment] 2017-04-30 13:24
Duplicate of https://github.com/gollum/gollum/issues/1052

**Closed by dometto** 2017-04-30 13:24 UTC
