### ISSUE TITLE
Macros cannot be nested

### ISSUE THREAD

**Issue by nlowe** [gollum/gollum-lib#125] opened 2014-12-22 15:03 UTC
I am not sure if this is supposed to be supported or not, but macros cannot be nested (that is, contained within other macros). For example, a file contains the following snippet:

```
<<Note("There is an example config file located <<SMBLink('here','\\some\server\subdir')>>")>>
```

I expect the `SMBLink` macro to be computed (which returns `<a class='externallink' href='file://///some/server/subdir' title='here' target='_blank'>here</a>`) and added inside of the `Note` macro.

Instead, it seems that gollum either absorbs the nested macro or fails at parsing it, because it renders something along the lines of 

``` html
<div style='font: normal 1em/1.5 sans-serif; background-color: rgb(222, 243, 254); border: 1px solid rgb(197, 215, 224); color: black; padding: 5px 5px 5px 45px; margin: 1ex 0pt; min-height: 35px;'>
         <div style='float: left; margin-left: -40px;'><img alt='Note' title='Note' src='/uploads/hgm_images/note.png' width='35' border='0' height='35'></div>
         <div><b>NOTE</b><br>There is an example config file located &gt;</div>
 </div>
```

**Expected Result**:

``` html
<div style='font: normal 1em/1.5 sans-serif; background-color: rgb(222, 243, 254); border: 1px solid rgb(197, 215, 224); color: black; padding: 5px 5px 5px 45px; margin: 1ex 0pt; min-height: 35px;'>
         <div style='float: left; margin-left: -40px;'><img alt='Note' title='Note' src='/uploads/hgm_images/note.png' width='35' border='0' height='35'></div>
         <div><b>NOTE</b><br>There is an example config file located <a class='externallink' href='file://///some/server/subdir' title='here' target='_blank'>here</a></div>
 </div>
```

```
```

**Comment by SkyCrawl** [comment] 2015-04-06 14:41
I think this issue is caused by the fact that [macro matching regexes](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/macro.rb) disregard nested macros... Which means that whether intended or not, the current version of Gollum doesn't support nested macros :).

**Comment by dometto** [comment] 2017-04-30 21:51
I think this would be too difficult to implement, for reasons mentioned above. :(

**Comment by bartkamphorst** [comment] 2017-05-01 13:14
I actually think this is challenging but doable. I vote to keep it open for a little bit longer.

**Comment by bartkamphorst** [comment] 2019-09-27 10:58
I've considered this some more but I don't think it is worth pursuing on a general level, at least not at this point. @nlowe's example of

```<<Note("There is an example config file located <<SMBLink('here','\\some\server\subdir')>>")>>```

where the nested macro is in the argument string can still be made to work though by parsing the argument string that is given to the Note() macro (i.e. `"There is an example config file located <<SMBLink('here','\\some\server\subdir')>>"`) in the Note() macro implementation (i.e. in `#render`) and instantiating and calling the SMBLink Macro directly from there.

Closing this then as a WontFix, with apologies.

**Closed by bartkamphorst** 2019-09-27 10:58 UTC
