### ISSUE TITLE
gollum-lib 5.x mistakenly allowed for use with gollum 4.x

### ISSUE THREAD

**Issue by karlredman** [gollum/gollum-lib#282] opened 2017-08-11 08:22 UTC
Hi, I'm looking for the code that re formats tag links int URLs so that I can monkey patch this for my own project at the very least. I haven't been able to find the change in this release so far. 

*  Relative links (tags) are being reformatted to replace spaces with '+' characters in gollum-lib v5.0.a.3 for the URL formatting. This is a change from gollum-lib v4.2.7
    * I'm pretty sure this change also bumped some handler code somewhere
* I recall seeing this issue before but can't find it. 
* I think this is a bug.
* Tags with spaces are processed to render the correct file with gollum-lib v4.2.7

## Correct Behavior
* Gollum v4.1.[1|2] / gollum-lib v4.2.7
    * "[[Filename With Spaces]]" 
        * yields URL: "Filename-With-Spaces"
        * Shows file: "Filename With Spaces.ext"

## Incorrect Behavior for Relative URL
* Gollum v4.1.2 / gollum-lib v5.0.a.3
    * "[[Filename With Spaces]]" 
        * yields URL "/create/Filename%2BWith%2BSpaces.ext"
        * **Creates file:** "Filename-With-Spaces-dot-ext.ext"

**Comment by dometto** [comment] 2017-08-12 14:19
The correct behavior on `5.x` is documented here: https://github.com/gollum/gollum/wiki/5.0-release-notes#filename-handling

The behavior your describing is a consequence of using the `4.x` line of `gollum` with the `5.x` branch of `gollum-lib`. `gollum 4.x` still expects the lib to do whitespace substitution, which leads to problems resolving the page name. NB: not replacing spaces is the intended behavior on `5.x`.

When doing a `gem install gollum`, the `gollum-lib` dependency should *not* resolve to `gollum-lib 5.x alpha`. As far as I can see, that is indeed not the case, so I assume you're manually installing or requiring the `5.x alpha` branch. Again, for the record, I strongly advise against this. `gollum-lib 5.x` is intended for use future use with `gollum 5.x`.

**Comment by dometto** [comment] 2017-08-12 14:22
I just saw that `gollum`'s `gemspec` is allowing use with `gollum-lib >= 4.2.7`. That's a mistake, and should be `gollum-lib >=  4.2.7, < 5`.

**Comment by karlredman** [comment] 2017-08-12 23:59
Thank you for looking into this. Manually installing gollum-lib 4.2.7 worked fine. I'd noticed the gemspec file and assumed that was correct.

Just for clarification I've repeatedly tested this with complete uninstalls and reinstalls. the gem install for gollum 4.1.2 was automatically pulling in gollum-lib 5.0.a.3 -at least using the method shown below.

```
sudo gem uninstall -aIx github-markup github-markdown gollum-lib gollum-grit_adapter gollum kramdown gitlab-grit grit creole nokogiri
```

```
gem install gollum

	  Fetching: gemojione-3.3.0.gem (100%)
	  Successfully installed gemojione-3.3.0
	  Fetching: github-markup-1.6.1.gem (100%)
	  Successfully installed github-markup-1.6.1
	  Fetching: mini_portile2-2.2.0.gem (100%)
	  Successfully installed mini_portile2-2.2.0
	  Fetching: nokogiri-1.8.0.gem (100%)
	  Building native extensions.  This could take a while...
	  Successfully installed nokogiri-1.8.0
	  Fetching: charlock_holmes-0.7.3.gem (100%)
	  Building native extensions.  This could take a while...
	  Successfully installed charlock_holmes-0.7.3
	  Fetching: gitlab-grit-2.8.1.gem (100%)
	  Successfully installed gitlab-grit-2.8.1
	  Fetching: gollum-grit_adapter-1.0.1.gem (100%)
	  Successfully installed gollum-grit_adapter-1.0.1
	  Fetching: gollum-lib-5.0.a.3.gem (100%)
	  Successfully installed gollum-lib-5.0.a.3
	  Fetching: kramdown-1.9.0.gem (100%)
	  Successfully installed kramdown-1.9.0
	  Fetching: tilt-2.0.8.gem (100%)
	  Successfully installed tilt-2.0.8
	  Fetching: gollum-4.1.2.gem (100%)
	  Successfully installed gollum-4.1.2
	  Parsing documentation for charlock_holmes-0.7.3
	  Installing ri documentation for charlock_holmes-0.7.3
	  Parsing documentation for gemojione-3.3.0
	  Installing ri documentation for gemojione-3.3.0
	  Parsing documentation for github-markup-1.6.1
	  Installing ri documentation for github-markup-1.6.1
	  Parsing documentation for gitlab-grit-2.8.1
	  Installing ri documentation for gitlab-grit-2.8.1
	  Parsing documentation for gollum-4.1.2
	  Installing ri documentation for gollum-4.1.2
	  Parsing documentation for gollum-grit_adapter-1.0.1
	  Installing ri documentation for gollum-grit_adapter-1.0.1
      ```

**Closed** 2017-08-13 01:08 UTC

**Comment by dometto** [comment] 2017-08-13 08:07
Ah, thanks for the report. That's very odd, in my environment it's correctly resolving the dependency. I think the rubygems API specifies that alpha and beta releases are not to be automatically resolved. In either case it should no longer occur when I update the gemspec.
