### ISSUE TITLE
During the post-commit hook execution the changes are not yet synced to the repository

### ISSUE THREAD

**Issue by pinkeen** [gollum/gollum-lib#225] opened 2016-10-20 14:55 UTC
I want to execute a bash script during post-commit event. The bash script is using the cli git. It's supposed to create a merge request in case of conflicts.

It seems that during execution of the script the file being modified is already changed on the filesystem but no commit is made according to the cli git.

Is there a way to sync the index to filesystem before calling the hook?

**Comment by dometto** [comment] 2017-04-30 13:20
That's odd. Hooks are triggered [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/committer.rb#L171), clearly after the commit has been executed. Did you ever make any progress with this, @pinkeen?

**Comment by pinkeen** [comment] 2017-06-04 18:20
I ended up doing a push/pull script (with automatic PR creation on conflict) in a cronjob.

**Comment by bartkamphorst** [comment] 2018-11-15 16:11
Duplicate of https://github.com/gollum/gollum-lib/issues/294. Explanation and workaround can be found in that issue; we're still considering a fix.

**Closed by bartkamphorst** 2018-11-15 16:11 UTC
