### ISSUE TITLE
Succesful installation of gollum on Windows 10 Home Single Language

### ISSUE THREAD

**Issue by rbnmx** [gollum/gollum-lib#234] opened 2017-01-08 05:09 UTC
From the README.md
>Will not work on Windows with the default grit adapter, but might work via JRuby (please let us know!)

It works!

![2017-01-07_2256](https://cloud.githubusercontent.com/assets/5141189/21747501/20e6e6f8-d52e-11e6-9d34-cdf094d7ad05.png)

![2017-01-07_2300](https://cloud.githubusercontent.com/assets/5141189/21747497/10a0ad7e-d52e-11e6-8708-3a7f8cf70c5f.png)

**Comment by bartkamphorst** [comment] 2017-01-08 20:04
Have you tried any of the functionalities? Last time I checked I got various errors, mostly related to path issues.

**Comment by rbnmx** [comment] 2017-01-08 23:03
So far, only tried the command `gollum`. It ran successfully, I think

![2017-01-08_1648](https://cloud.githubusercontent.com/assets/5141189/21754253/616f6224-d5c2-11e6-9791-ff7de98de277.png)

I'm progressing slowly but I'll keep sharing other relevant progress. By the way if you could share tips to about resources to do the jump from solo/end-user programmer to open-source contributor will help me to progress fastly.

**Comment by dometto** [comment] 2017-01-19 14:13
Thanks for letting us know, that's great news! I'll close this now because we're tracking Windows progress over at the [gollum]{https://github.com/gollum/gollum) bugtracker, using the `[Windows]` prefix. Perhaps you could try and see if some of the bugs reported there are still reproducable?

There are some contributor guidelines in the gollum and gollum-lib readme, as well as [here](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md). Also see [here](https://guides.github.com/activities/contributing-to-open-source/).

**Closed by dometto** 2017-01-19 14:13 UTC
